import { ethers } from "https://esm.sh/ethers@6.13.4";
import EthereumProvider from "https://esm.sh/@walletconnect/ethereum-provider@2.17.2";

const CONTRACT_ADDRESS = "PASTE_CONTRACT_ADDRESS_HERE";
const PROJECT_ID = "fe55ea601c3e7e0925c0b33723d6b158";
const ABI = [
  "function mint(uint256 amount) external payable",
  "function PRICE() view returns (uint256)",
  "function minted(address user) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function tokenURI(uint256 tokenId) view returns (string)"
];

const MAINNET_HEX="0x1", MAINNET_ID=1, MAX_SUPPLY=10000, DEFAULT_PRICE_ETH="0.00005";
let wcProvider=null, provider=null, signer=null, contract=null, account=null, cachedPriceWei=null, cachedAlreadyMinted=0n;
const $=id=>document.getElementById(id);
const walletEl=$("wallet"),statusEl=$("status"),amountInput=$("amountInput"),progressBar=$("progressBar"),mintedText=$("mintedText"),priceText=$("priceText"),galleryEl=$("gallery"),openseaLink=$("openseaLink"),etherscanLink=$("etherscanLink"),walletModal=$("walletModal"),balanceEl=$("balanceText"),mintedByWalletEl=$("mintedByWalletText"),networkEl=$("networkText");
function status(m){statusEl.textContent=m} function openModal(){walletModal.classList.remove("hidden")} function closeModal(){walletModal.classList.add("hidden")}
function ipfsToHttp(u){return u&&u.startsWith("ipfs://")?"https://ipfs.io/ipfs/"+u.replace("ipfs://",""):u}
function getAmount(){let a=Number(amountInput.value);if(!Number.isInteger(a)||a<1)a=1;if(a>100)a=100;amountInput.value=a;return a}
function setLinks(){if(CONTRACT_ADDRESS!=="PASTE_CONTRACT_ADDRESS_HERE"){etherscanLink.href=`https://etherscan.io/address/${CONTRACT_ADDRESS}`;openseaLink.href=`https://opensea.io/assets/ethereum/${CONTRACT_ADDRESS}`}}
async function setupProvider(eip1193Provider, selectedAccount){provider=new ethers.BrowserProvider(eip1193Provider);signer=await provider.getSigner();account=selectedAccount||await signer.getAddress();contract=new ethers.Contract(CONTRACT_ADDRESS,ABI,signer);walletEl.textContent=account.slice(0,6)+"..."+account.slice(-4);status("Connected");setLinks();closeModal();await loadStats();await loadProgress();await refreshPrice()}
async function connectBrowserWallet(){try{if(CONTRACT_ADDRESS==="PASTE_CONTRACT_ADDRESS_HERE")throw new Error("Встав адресу контракту в app.js");if(!window.ethereum)throw new Error("MetaMask/Rabby extension not found");const chainId=await window.ethereum.request({method:"eth_chainId"});if(chainId!==MAINNET_HEX)await window.ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:MAINNET_HEX}]});const accounts=await window.ethereum.request({method:"eth_requestAccounts"});await setupProvider(window.ethereum,accounts[0])}catch(e){console.error(e);status("Error: "+(e.shortMessage||e.message))}}
async function connectWalletConnect(){try{if(CONTRACT_ADDRESS==="PASTE_CONTRACT_ADDRESS_HERE")throw new Error("Встав адресу контракту в app.js");wcProvider=await EthereumProvider.init({projectId:PROJECT_ID,chains:[MAINNET_ID],optionalChains:[MAINNET_ID],showQrModal:true,metadata:{name:"Onchain Flamingo Eggs",description:"Flamingo Eggs mint site",url:window.location.origin,icons:[window.location.origin+"/favicon.png"]}});await wcProvider.connect();await setupProvider(wcProvider,(wcProvider.accounts||[])[0]);wcProvider.on("accountsChanged",async(accounts)=>{if(accounts&&accounts[0])await setupProvider(wcProvider,accounts[0])});wcProvider.on("disconnect",disconnectWallet)}catch(e){console.error(e);status("Error: "+(e.shortMessage||e.message))}}
async function disconnectWallet(){try{if(wcProvider)await wcProvider.disconnect()}catch(e){}wcProvider=null;provider=null;signer=null;contract=null;account=null;cachedPriceWei=null;cachedAlreadyMinted=0n;walletEl.textContent="not connected";status("Disconnected");await refreshPrice()}
async function loadStats(){try{if(!provider||!account)return;const net=await provider.getNetwork();networkEl.textContent=net.chainId===1n?"Ethereum":"Wrong network";balanceEl.textContent=Number(ethers.formatEther(await provider.getBalance(account))).toFixed(4)+" ETH";if(contract) mintedByWalletEl.textContent=(await contract.minted(account)).toString()}catch(e){}}
async function refreshPrice(){try{const amount=BigInt(getAmount());if(contract&&account){cachedAlreadyMinted=await contract.minted(account);cachedPriceWei=await contract.PRICE()}if(!cachedPriceWei){priceText.textContent=amount===1n?"FREE":(Number(amount-1n)*Number(DEFAULT_PRICE_ETH)).toFixed(5).replace(/0+$/,'').replace(/\.$/,'')+" ETH";return}let paid=amount;if(cachedAlreadyMinted===0n)paid=paid>0n?paid-1n:0n;priceText.textContent=paid===0n?"FREE":ethers.formatEther(cachedPriceWei*paid)+" ETH"}catch(e){}}
async function loadProgress(){if(!contract)return;const m=Number(await contract.totalSupply());mintedText.textContent=m+" / "+MAX_SUPPLY;progressBar.style.width=Math.min(100,m/MAX_SUPPLY*100)+"%"}
async function mint(){try{if(!contract){status("Connect wallet first");return}const amount=getAmount(),already=await contract.minted(account),price=await contract.PRICE();let paid=BigInt(amount);if(already===0n)paid=paid>0n?paid-1n:0n;status("Confirm mint in wallet...");const tx=await contract.mint(amount,{value:price*paid});status("Transaction sent: "+tx.hash);await tx.wait();status("Mint success!");await loadStats();await loadProgress();await refreshPrice();await loadGallery()}catch(e){console.error(e);status("Error: "+(e.shortMessage||e.message))}}
async function loadGallery(){try{if(!contract){status("Connect wallet first");return}galleryEl.innerHTML="<p class='galleryNote'>Loading minted NFTs...</p>";const supply=Number(await contract.totalSupply());if(supply===0){galleryEl.innerHTML="<p class='galleryNote'>No minted NFTs yet.</p>";return}const ids=[];for(let i=supply;i>=Math.max(1,supply-19);i--)ids.push(i);const cards=await Promise.all(ids.map(async id=>{try{const uri=await contract.tokenURI(id),meta=await(await fetch(ipfsToHttp(uri))).json(),img=meta.image,name=meta.name||("Flamingo Egg #"+id);return `<article class="nftCard"><img src="${img}" alt="${name}"><div>${name}<small>Token #${id}</small></div></article>`}catch(e){return `<article class="nftCard"><div>Token #${id}<small>Metadata loading...</small></div></article>`}}));galleryEl.innerHTML=cards.join("")}catch(e){galleryEl.innerHTML="<p class='galleryNote'>Gallery error</p>"}}
$("connectWalletBtn").onclick=openModal;$("closeModalBtn").onclick=closeModal;$("browserWalletBtn").onclick=connectBrowserWallet;$("walletConnectBtn").onclick=connectWalletConnect;$("disconnectBtn").onclick=disconnectWallet;$("mintBtn").onclick=mint;$("loadGalleryBtn").onclick=loadGallery;$("minusBtn").onclick=async()=>{amountInput.value=Math.max(1,Number(amountInput.value||1)-1);await refreshPrice()};$("plusBtn").onclick=async()=>{amountInput.value=Math.min(100,Number(amountInput.value||1)+1);await refreshPrice()};amountInput.oninput=refreshPrice;refreshPrice();setLinks();setInterval(loadProgress,15000);
